---
# Source: cluster-autoscaler/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: "aws-cluster-autoscaler"
    app.kubernetes.io/name: "aws-cluster-autoscaler"
    app.kubernetes.io/managed-by: "Tiller"
    helm.sh/chart: "cluster-autoscaler-6.0.0"
  name: aws-cluster-autoscaler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "aws-cluster-autoscaler"
      app.kubernetes.io/name: "aws-cluster-autoscaler"
  maxUnavailable: 1
  # minAvailable: 2
  