extraScrapeConfigs: |
  - job_name: anchore-api
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - anchore-anchore-engine:8228
    basic_auth:
      username: admin
      password: anchore