global:
  edition: ce
  hosts:
    https: false
  ingress:
    configureCertmanager: false
    tls:
      enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/ingress.provider: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 512m
      nginx.ingress.kubernetes.io/proxy-connect-timeout: 15
      nginx.ingress.kubernetes.io/proxy-read-timeout: 600
certmanager:
  install: false
prometheus:
  install: false
gitlab-runner:
  install: false
nginx-ingress:
  enabled: false
